export const GET_USERINFO = 'getUserInfo'
export const EDIT_USERINFO = 'editUserInfo'
export const ADD_ADDRESS = 'addAddress'
export const DELETE_ADDRESS = 'deleteAddress'
export const GET_MYORDERS = 'getMyOrders'
export const GET_ORDERDETAIL = 'getOrderDetail'